Pull request 4
lauw26/Sparta-Core-Project-1 pull request #4
Opened 2017-08-12 11:18 UTC by lauw26

Implemented total function to find the total value of player and dealer hands and storing them
Implemented comparison method to determine the winner base on the value of player and dealer hands.

2017-08-13 08:22 UTC, richgurney requested changes
Hi Will, the code is looking really good well done. Really neat and tidy and well formatted. 

I wont merge this yet as the results are inputed into the console. Don't forget a USER doesn't know the console is there.

Can you add the output that your sending to the console to the page. Lets make it clear to the USER whats going on. 

Really well done though. Great work

2017-08-13 08:26 UTC, lauw26 commented
ok will work on that after the finishing the bet button

2017-08-13 10:37 UTC, lauw26 commented
Used boot strap to position buttons and output, using divs to output my results from backend. 
Displays user and dealer hand total as well as outcome

2017-08-14 11:01 UTC, richgurney approved these changes

2017-08-14 11:01 UTC, merged